# Generated by Django 3.1.3 on 2020-12-21 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
