# Generated by Django 3.1.3 on 2020-12-21 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20201221_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='character_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character'),
        ),
    ]
